#!/bin/bash

mkdir -p my_project

cd my_project

git init

# change default editor from vi to vim or nano
git config --global core.editor nano

#git config --global --edit
git config --global user.name "Mark Waudby"
git config --global use.email mark.waudby@gmail.com
git commit --m --reset-author

git branch -m <name>
# change default name (master) to e.g. main, trunk, development

git add *

git commit -m <message>

git log -p -x
# limit the number of entries to the value of x